/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cas;

import cas.functions;
import cas.signIn;
import java.awt.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class HODInterface extends javax.swing.JFrame {
    String dept = "";
    Object addrow[];
    /**
     * Creates new form HODInterface
     */
    public HODInterface() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attendancebutton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        attendancebutton.setText("Check Attendance");
        attendancebutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        attendancebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendancebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(attendancebutton);
        attendancebutton.setBounds(390, 30, 140, 27);

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(290, 320, 80, 25);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 320, 80, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lecturer", "Course"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 90, 240, 210);

        jLabel1.setText("Lecturer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 120, 51, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Choose Lecturer-" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(80, 120, 150, 20);

        jLabel2.setText("Course");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 170, 51, 16);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Choose Course-" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(80, 170, 150, 20);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 230, 70, 25);

        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(150, 230, 80, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            DefaultTableModel td = (DefaultTableModel)jTable1.getModel();
            int row = jTable1.getSelectedRow();
            td.removeRow(row);
        }
        catch(Exception e){
            DefaultTableModel td = (DefaultTableModel)jTable1.getModel();
            if (td.getRowCount() == 0){
                JOptionPane.showMessageDialog(rootPane, "Empty table");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if ((jComboBox1.getSelectedIndex() == 0) || (jComboBox2.getSelectedIndex() == 0)){
            JOptionPane.showMessageDialog(rootPane, "Details not complete");
        }else{
            String name = jComboBox1.getSelectedItem().toString();
            String course = jComboBox2.getSelectedItem().toString();
            Object addrow[] = {name, course};
            if (jTable1.getRowCount() == 0){
                DefaultTableModel td = (DefaultTableModel)jTable1.getModel();
                td.addRow(addrow);
                jComboBox1.setSelectedIndex(0);
                jComboBox2.setSelectedIndex(0);
            }else{
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    String left = jTable1.getValueAt(i, 0).toString();
                    String right = jTable1.getValueAt(i, 1).toString();
                    if ((left == name) && (right == course)){
                        JOptionPane.showMessageDialog(rootPane, "Lecturer already assigned to course");
                        break;
                    }else{
                        DefaultTableModel td = (DefaultTableModel)jTable1.getModel();
                        td.addRow(addrow);
                        jComboBox1.setSelectedIndex(0);
                        jComboBox2.setSelectedIndex(0);
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String dept = "";
        switch (signIn.retreived_dept){
            case "Computer Science" ->  dept = "csc";
            case "Electrical Engineering" -> dept = "eee";
            case "Mechanical Engineering" -> dept  = "mee";
            default -> {
            }
        }
        System.out.println(dept);
        try{
            DefaultTableModel td = (DefaultTableModel)jTable1.getModel();
            int rowcount = td.getRowCount();
            if (rowcount != 0){
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cas","root","$ideWalks3500");
                for (int i = 0; i<rowcount;i++){
                    String lecturer = td.getValueAt(i, 0).toString();
                    String course = td.getValueAt(i, 1).toString();
                    String statement = String.format("insert into %s(name, identity, %s) values(?,?,?)",dept,course);
                    PreparedStatement ps2 = con.prepareStatement(statement);
                    ps2.setString(1, lecturer);
                    ps2.setString(2, "lecturer");
                    ps2.setInt(3, 1);
                    ps2.executeUpdate();
                }
                JOptionPane.showMessageDialog(rootPane, "Lecturers Assigned");
                con.close();
                int rowCount = td.getRowCount();
                while (rowCount != 0){
                    td.removeRow(rowCount-1);
                    rowCount -= 1;
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Empty table");
            }

        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Database Issue");
            System.out.println("error" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void attendancebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendancebuttonActionPerformed
        DeptAttendance Attendance = new DeptAttendance();
        Attendance.show();
        Attendance.setVisible(true);
    }//GEN-LAST:event_attendancebuttonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved

    }//GEN-LAST:event_formMouseMoved

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        System.out.println(signIn.retreived_dept);
        String[] courselist = functions.courses(signIn.retreived_dept);
        for(int i = 1; i < courselist.length; i++){
            jComboBox2.addItem(courselist[i]);
        }  
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cas","root","$ideWalks3500");
            PreparedStatement ps = con.prepareStatement("select * from faculty");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                if (rs.getString(3).equals(signIn.retreived_dept)){
                String name = rs.getString(1);
                jComboBox1.addItem(name);
                }
            }
                
            }catch(Exception e) {
            System.err.println();
            System.out.println("test");
            //JOptionPane.showMessageDialog(rootPane, "No Lecturers Created");
            System.out.println("error" + e.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HODInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HODInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HODInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HODInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HODInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attendancebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
